add header
RomarioNik/test-project pull request #3
Opened 2022-11-20 19:01 UTC by TanyaEdyna

2022-11-21 13:33 UTC, RomarioNik commented
Добавьте переменные, и вынесите основные стили в файл common.scss
Но перед этим Вам нужно будет обновить проект (я внес там изменения в ветку main).
Только чтоб обновления не затерли ваш Header и остальные файлы)

2022-11-21 22:55 UTC, RomarioNik requested changes

2022-11-21 22:55 UTC, RomarioNik commented on src/partials/index2.html
> +<h1>test</h1>
Удалите это файл

2022-11-21 22:55 UTC, RomarioNik commented on src/sass/_common.scss
> +body {
На body нужны базовые стили шрифта (weight, size, line-height и тд.)

2022-11-21 22:55 UTC, RomarioNik commented on src/sass/_common.scss
> +    font-style: inherit;
Button не наследует font-family, а не style

2022-11-21 22:55 UTC, RomarioNik commented on src/sass/_header.scss
> +  margin: 0 auto;
margin: 0 auto;
вынесите в основные стили класса .container

2022-11-21 22:55 UTC, RomarioNik commented on src/sass/_header.scss
> +  padding: 36px 15px;
padding: 36px 15px; (отсюда это удалите)
вынесите в основные стили контейнера padding: 0 15px;
а 36px добавьте в padding top и bottom в ссылки в основной навигации nav

2022-11-21 22:55 UTC, RomarioNik commented on src/sass/_common.scss
> +    padding: 0;
Удалите  margin: 0;  и  padding: 0; их по умолчанию вроде там нет
Добавьте лучше display: inline-block;

2022-11-22 12:27 UTC, RomarioNik requested changes

2022-11-22 12:27 UTC, RomarioNik commented on src/sass/index.scss
> -@import './footer';
В main уже есть footer.
Удали у себя, пожалуйста)

2022-11-24 14:06 UTC, TanyaEdyna commented on src/sass/_common.scss
> +body {
я передивилась макет, не бачу сенсу на body ставити загальний weight, size, line-height, тому що по макети ці властивості скрізь різні. На мою думку, краще буде задавати їх кожному елементу окремо

2022-11-24 14:33 UTC, RomarioNik approved these changes

2022-11-24 14:34 UTC, merged