Gc branch
RomarioNik/test-project pull request #8
Opened 2022-12-02 15:17 UTC by acrcane

2022-12-03 13:20 UTC, TanyaEdyna requested changes

2022-12-03 13:20 UTC, TanyaEdyna commented on src/partials/first-section.html
> +    <h2 class="invisibility">Presentation</h2>
h2 тут не потрібен, тому що в секції є заголовок

2022-12-03 13:20 UTC, TanyaEdyna commented on src/partials/first-section.html
> +                    <h3 class="big-title-section">Find a gift for your wife or girlfriend</h3>
це має бути h1

2022-12-03 13:20 UTC, TanyaEdyna commented on src/partials/first-section.html
> +                <img src="./images/first-section-img.jpg" alt="Presentation" class="presintation-img" style="width:700;">
в img потрібно вказати width, style прибрати

2022-12-03 13:20 UTC, TanyaEdyna commented on src/partials/first-section.html
> +                <img src="./images/first-section-img1.jpg" alt="Presentation" class="presintation-img" style="width:700;">
в img потрібно вказати width, style прибрати

2022-12-03 13:20 UTC, TanyaEdyna commented on src/partials/first-section.html
> +                    <h3 class="title-section">How we work</h3>
це h2

2022-12-03 13:20 UTC, TanyaEdyna commented on src/sass/_section-first.scss
> +    font-family: 'Gilroy';
на body є загальні fonts - на проекті у нас Roboto

2022-12-03 13:20 UTC, TanyaEdyna commented on src/sass/_section-first.scss
> +    text-transform: uppercase;
text-transform: uppercase; дубляж на 50

2022-12-04 14:55 UTC, acrcane commented
g

2022-12-04 16:16 UTC, merged